version: 2
jobs:
  build:
    working_directory: ~/HartreeFockBogoliubov.jl
    docker:
      - image: julia:latest
    steps:
      - checkout
      - run:
          name: greeting
          command: "julia --version"
      - run:
          name: dependency
          command: |
            julia --project -e 'import Pkg; Pkg.build()'
      - run:
          name: test
          command: |
            julia --project --check-bounds=yes -e 'import Pkg; Pkg.test(; coverage=false)'